### ISSUE TITLE
Are the issues mentioned in https://www.reddit.com/r/Python/comments/876msl/sanic_python_web_server_thats_written_to_die_fast/ addressed

### ISSUE THREAD

**Issue by blueray453** [huge-success/sanic#1700]
I tried to ask this question in https://community.sanicframework.org/

But for some reason they did not approve my account yet. https://github.com/huge-success/sanic/issues/1697

So my questions is, Are the issues mentioned in https://www.reddit.com/r/Python/comments/876msl/sanic_python_web_server_thats_written_to_die_fast/ addressed yet. I got an answer in my last question which says 

_Some issues have been addressed_

I would like someone who understand this project to answer this question. The last guy was not particular enough. He without understanding or addressing the issue, closed it.

**Comment by sjsadowski** [comment]
Please read the documentation. Identify which issues you have questions about. Ask specific questions. The entirety of your post is made up of a triple negative and and asking about a reddit post from over a year ago which covers quite a bit of ground. I'm closing this because you don't actually ask a specific question, you ask about a reddit post which is mostly a giant complaint session about a project that was half-abandoned at the time and has subsequently had more interaction.

To be clear: A) some of the issues in that reddit post have been addressed B) some of the issues in that reddit post were never seen as issues except for those raised by the author of the post and C) There have been massive changes to the Sanic project since that post was made.

RTFM, and decide for yourself whether or not the framework is ready for production use, how you want to implement it, and if you have specific issues, please post them here.

**Comment by blueray453** [comment]
What a toxic disfuctional community. Can not believe RTFM people still exist.

**Comment by sjsadowski** [comment]
@blueray453 I'm sorry you feel that way. Perhaps if you asked specific questions, you could get specific answers.

**Comment by blueray453** [comment]
To be specific, I was searching for a framework which did not need nginx or gunicorn. I was very impressed with this project. I decided to do a little research before using it. I found the Reddit post. Most of the issues he found is clearly mentioned there so I did not find the need to copy paste it here. 

What, I needed to hear is that most critical issues are addressed and the project is now in good hands. And some issue links from this project which are marked closed.

I decided to ask the question in your forum because github issues is definitely not a good place to ask these sort of question. The last person (probably borderline retrded) said, he did not understand the question. Then closed the question. If you don't understand a question then why do you close it?

Then I asked the question here and you said -
> The entirety of your post is made up of a triple negative

Again you said -

> RTFM

First of all it is called documentation and not manual. And you probably did not read it either. I know it because some of the issues in the reddit post are not mentioned in the documentation, and it should not be in the documentation. And let me tell you somethings, there are two type of documentations.

1. Good
2. Shitty, because of which sites like stackoverflow exists.

Anyways, I am sure you also use some open source project. You will also not like to hear RTFM from them.

People like you give software developers bad name. Because of people like you, we have to hear software guys do not have people skill.

Good luck having a real job, good luck with your toxic community.

**Comment by sjsadowski** [comment]
I have locked this issue as name calling, being pedantic, and still failing to identify what specific issues you'd like answers to that aren't addressed in the documentation don't further the conversation.
