### ISSUE TITLE
Sanic in Snap package error with logging even if logging disabled

### ISSUE THREAD

**Issue by btegs** [huge-success/sanic#846]
Here is a very basic server.py script for Sanic:

```
#!/usr/bin/env python3

from sanic import Sanic
from sanic import response

app = Sanic(__name__)

@app.route("/")
async def test(request):
    return response.json({"sanic": "Py3 Snap!"})

if __name__ == '__main__':
    app.run(host="0.0.0.0", port=8000, debug=False, log_config=None)
```
and here is my snapcraft.yaml:

```
name: py3snap
version: '1499857382'
summary: Single-line elevator pitch for Python 3 snap test
description: This is the description for the test Python 3 snap test
confinement: strict
grade: devel

apps:
  py3snap:
    command: bin/py3snap-server
    # daemon: simple
    plugs: [network-bind]
    # restart-condition: always

parts:
  py3snap:
    plugin: python
    python-version: python3
    requirements: /home/brian/Projects/py3snap/requirements.txt
    source: /home/brian/Projects/py3snap
    organize:
      /home/brian/Projects/py3snap/server: bin/py3snap-server
```

My requirements.txt is pretty simple:

```
uvloop
sanic
```

When creating a Snap package for Ubuntu 16.04 via snapcraft, I still get a logging error even if log_config is disabled:

```
brian@ubuntu:~/Projects/py3snap/snaps$ sudo snap install py3snap_1499857382_amd64.snap --dangerous
[sudo] password for brian: 
py3snap 1499857382 installed
brian@ubuntu:/$ sudo py3snap
Traceback (most recent call last):
  File "/snap/py3snap/x1/usr/lib/python3.5/logging/config.py", line 558, in configure
    handler = self.configure_handler(handlers[name])
  File "/snap/py3snap/x1/usr/lib/python3.5/logging/config.py", line 731, in configure_handler
    result = factory(**kwargs)
  File "/snap/py3snap/x1/usr/lib/python3.5/logging/handlers.py", line 202, in __init__
    BaseRotatingHandler.__init__(self, filename, 'a', encoding, delay)
  File "/snap/py3snap/x1/usr/lib/python3.5/logging/handlers.py", line 57, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/snap/py3snap/x1/usr/lib/python3.5/logging/__init__.py", line 1008, in __init__
    StreamHandler.__init__(self, self._open())
  File "/snap/py3snap/x1/usr/lib/python3.5/logging/__init__.py", line 1037, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
OSError: [Errno 30] Read-only file system: '/access.log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/py3snap/x1/bin/py3snap-server", line 6, in <module>
    app = Sanic(__name__)
  File "/snap/py3snap/x1/lib/python3.5/site-packages/sanic/app.py", line 33, in __init__
    logging.config.dictConfig(log_config)
  File "/snap/py3snap/x1/usr/lib/python3.5/logging/config.py", line 795, in dictConfig
    dictConfigClass(config).configure()
  File "/snap/py3snap/x1/usr/lib/python3.5/logging/config.py", line 566, in configure
    '%r: %s' % (name, e))
ValueError: Unable to configure handler 'accessTimedRotatingFile': [Errno 30] Read-only file system: '/access.log'

```
As you can see, I have error logging to off in the .run command but it is still looking for it. Is this a known issue to still look for log files even if disabled?

**Comment by btegs** [comment]
Is there a way to run this script without it automatically creating a blank access.log and error.log? That seems to be the problem here.

**Comment by r0fls** [comment]
@btegs this looks like a bug, but as a work around you should be able to pass the `log_config` variable to app: `app = Sanic(__name__, log_config=None)`

**Comment by btegs** [comment]
@r0fls - It still has the same error as by default Sanic will try to create a blank access.log and error.log on boot.

Maybe there should be a code change to check for the log_config on start and don't even try to create those two log files no matter what. If log_config is missing or is set manually to anything besides None, then it should do the traditional creation of a blank access.log and error.log.

I really want to get my app into a Snap package where I don't need an access.log and any errors that I would have would hopefully be fixed in development or through something like nginx.

**Comment by zenixls2** [comment]
https://github.com/channelcat/sanic/blob/master/sanic/config.py
the problematic accessTimedRotatingFile has been removed in the master branch,
but still exist in v0.5.4.
maybe you could switch to use master branch version,
or add to your file top before Sanic inits:
```python
from sanic.config import LOGGING
LOGGING['handlers'].pop('accessTimedRotatingFile')
LOGGING['handlers'].pop('errorTimedRotatingFile')
LOGGING['disable_existing_loggers'] = False
```
(even if we don't use these handlers in loggers, it seems python still did some initialization on the handlers.)

Wish this could help.

**Comment by btegs** [comment]
I'm sure you know what it is, but if you don't, Snap packages are these all-in-one sandboxed environments where it includes all of the files and libraries in one file. Since the file and its contents are read only, you cannot write within the environment and on top of that, you cannot get file access outside of it and any other processes cannot get file access inside of it. Typical sandboxing stuff.

So this poses an interesting question. Should Sanic by default not do access or error logs unless specified in app.run()? Do people really need an access or error log in a production environment? I say this because access, if important, is better suited logged in a database or through an external source like Google Analytics. As for errors, it could be the same way with database storage and logging via Apache or nginx. Even with log_config set to None, the terminal will still spit out errors (like recently with a missing favicon.ico) and nginx will store those in its own error.log.
